name: automerge
on: 
  pull_request: 
    branches: 
      - master
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 21
        method: squash

  
   
