
name: publish

on: 
 pull_request:
  paths: 
   - 'js/foo/bar/**'
 
jobs:
  build:
    name: run script
    runs-on: ubuntu-latest
    strategy:
     matrix:
      bash_script: [license_check, others]
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.bash_script }}   
        run: ./bash_script ${{ matrix.bash_script }}
 
 
