
name: publish

on: push
 
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: license check    
        id: license_check
        run: ./bash_script ${{steps.id}}
        env: 
          step: ${{steps.id}}
 
